version: "2"         # required to adjust maintainability checks
plugins:
  eslint:
    enabled: true
    channel: "eslint-7"
    config:
      extensions:
        - .ts
        - .js
    checks:
      "@typescript-eslint/no-shadow":
         enabled: false
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
